### ISSUE TITLE
Error during validate after initial npx setup

### ISSUE THREAD

**Issue by moishinetzer** [remix-run/indie-stack#21]
**System:** Windows 10
**Node and Npm:** Latest versions

**Error:**
```
> test:e2e:run
> cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 'cypress run'

C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:117
      throw err;
      ^

Error: expected <NPM script name that starts server> <url or port> <NPM script name that runs tests>
example: start-test start 8080 test
see https://github.com/bahmutov/start-server-and-test#use

    at lazyAssLogic (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:110:14)
    at lazyAss (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:115:28)
    at Object.getArguments (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\start-server-and-test\src\utils.js:91:5)
    at Object.<anonymous> (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\start-server-and-test\src\bin\start.js:10:22)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.7.1
ERROR: "test:e2e:run" exited with 1.
🚨 Oops, remix.init failed
Error: Command failed: npm run validate
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at askSetupQuestions (C:\Users\Moish\Documents\Github Repos\my-remix-app\remix.init\index.js:92:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\Users\Moish\Documents\Github Repos\my-remix-app\remix.init\index.js:68:3)
    at async init (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli\commands.js:112:7)
    at async Object.create (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli\commands.js:82:7)
    at async run (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli.js:324:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2624,
  stdout: null,
  stderr: null
}
Error: Command failed: npx --yes @remix-run/dev@1.3.2 create --template remix-run/indie-stack
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at run (C:\Users\Moish\AppData\Local\npm-cache\_npx\82f938b29eb562d9\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\Moish\AppData\Local\npm-cache\_npx\82f938b29eb562d9\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9120,
  stdout: null,
  stderr: null
}
```

Initial setup is fine however at this stage in the setup it errors. 

**Extended Output:**
```
$ npx create-remix --template remix-run/indie-stack
💿 Welcome to Remix! Let's get you set up with a new project.

? Where would you like to create your app? ./my-remix-app
? Do you want me to run `npm install`? Yes
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

> postinstall
> remix setup node

Successfully setup Remix for node.

added 1089 packages, and audited 1090 packages in 1m

228 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
💿 Running remix.init script

> setup
> prisma migrate dev

Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"

SQLite database data.db created at file:./data.db?connection_limit=1

Applying migration `20220307190657_init`

The following migration(s) have been applied:

migrations/
  └─ 20220307190657_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (3.11.0 | library) to .\node_modules\@prisma\client in 94ms


Running seed command `node --require esbuild-register prisma/seed.ts` ...
Database has been seeded. 🌱

The seed command has been executed.


? Do you want to run the build/tests/etc to verify things are setup properly? Yes
Running the validate script to make sure everything was set up properly

> validate
> run-p "test -- --run" lint typecheck test:e2e:run


> pretest:e2e:run
> npm run build


> test
> vitest "--run"


> typecheck
> tsc -b && tsc -b cypress


> lint
> eslint --cache --cache-location ./node_modules/.cache/eslint .


> build
> run-s build:*


> build:css
> npm run generate:css -- --minify


 RUN  v0.7.4 C:/Users/Moish/Documents/Github Repos/my-remix-app


> generate:css
> tailwindcss -o ./app/styles/tailwind.css "--minify"


Done in 822ms.

> build:remix
> remix build

Building Remix app in production mode...
 √ app/utils.test.ts (2)

Test Files  1 passed (1)
     Tests  2 passed (2)
      Time  14.39s (in thread 5ms, 316859.42%)

Built in 3s

> test:e2e:run
> cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 'cypress run'

C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:117
      throw err;
      ^

Error: expected <NPM script name that starts server> <url or port> <NPM script name that runs tests>
example: start-test start 8080 test
see https://github.com/bahmutov/start-server-and-test#use

    at lazyAssLogic (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:110:14)
    at lazyAss (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\lazy-ass\index.js:115:28)
    at Object.getArguments (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\start-server-and-test\src\utils.js:91:5)
    at Object.<anonymous> (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\start-server-and-test\src\bin\start.js:10:22)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.7.1
ERROR: "test:e2e:run" exited with 1.
🚨 Oops, remix.init failed
Error: Command failed: npm run validate
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at askSetupQuestions (C:\Users\Moish\Documents\Github Repos\my-remix-app\remix.init\index.js:92:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\Users\Moish\Documents\Github Repos\my-remix-app\remix.init\index.js:68:3)
    at async init (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli\commands.js:112:7)
    at async Object.create (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli\commands.js:82:7)
    at async run (C:\Users\Moish\AppData\Local\npm-cache\_npx\0936179b381f03f9\node_modules\@remix-run\dev\cli.js:324:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2624,
  stdout: null,
  stderr: null
}
Error: Command failed: npx --yes @remix-run/dev@1.3.2 create --template remix-run/indie-stack
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at run (C:\Users\Moish\AppData\Local\npm-cache\_npx\82f938b29eb562d9\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\Moish\AppData\Local\npm-cache\_npx\82f938b29eb562d9\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9120,
  stdout: null,
  stderr: null
}
```

**Comment by kentcdodds** [comment]
I think this should fix it: https://github.com/remix-run/indie-stack/commit/ab8566b18441f1af43efded89fa51d0a83a0fe05

Could you verify that it's been fixed?

**Comment by moishinetzer** [comment]
```
  "scripts": {
    "build": "run-s build:*",
    "build:css": "npm run generate:css -- --minify",
    "build:remix": "remix build",
    "dev": "run-p dev:*",
    "dev:css": "npm run generate:css -- --watch",
    "dev:remix": "node --require ./mocks ./node_modules/.bin/remix dev",
    "format": "prettier --write .",
    "generate:css": "tailwindcss -o ./app/styles/tailwind.css",
    "postinstall": "remix setup node",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint .",
    "setup": "prisma migrate dev",
    "start": "remix-serve build",
    "start:mocks": "node --require ./mocks ./node_modules/.bin/remix-serve build",
    "test": "vitest",
    "test:e2e:dev": "start-server-and-test dev http://localhost:3000 \"cypress open\"",
    "pretest:e2e:run": "npm run build",
    "test:e2e:run": "cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 \"cypress run\"",
    "typecheck": "tsc -b && tsc -b cypress",
    "validate": "run-p \"test -- --run\" lint typecheck test:e2e:run"
  },
```
My Scripts


```
$ npm run validate

> validate
> run-p "test -- --run" lint typecheck test:e2e:run


> test
> vitest "--run"


> lint
> eslint --cache --cache-location ./node_modules/.cache/eslint .

> pretest:e2e:run
> npm run build


> typecheck
> tsc -b && tsc -b cypress


> build
> run-s build:*


 RUN  v0.7.4 C:/Users/Moish/Documents/Github Repos/my-remix-app


> build:css
> npm run generate:css -- --minify


> generate:css
> tailwindcss -o ./app/styles/tailwind.css "--minify"


Done in 677ms.

> build:remix
> remix build

Building Remix app in production mode...
 √ app/utils.test.ts (2)

Test Files  1 passed (1)
     Tests  2 passed (2)
      Time  9.76s (in thread 8ms, 128585.79%)

Built in 2.7s

> test:e2e:run
> cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 "cypress run"

1: starting server using command "npm run start:mocks"
and when url "[ 'http://localhost:8811' ]" is responding with HTTP status code 200
running tests using command "cypress run"


> start:mocks
> node --require ./mocks ./node_modules/.bin/remix-serve build  

🔶 Mock server running
SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)      
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\esbuild-register\dist\node.js:2262:9)  
    at Object.extensions..js (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\esbuild-register\dist\node.js:4801:24)
    at Module.load (node:internal/modules/cjs/loader:975:32)    
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.7.1
Error: server closed unexpectedly
    at ChildProcess.onClose (C:\Users\Moish\Documents\Github Repos\my-remix-app\node_modules\start-server-and-test\src\index.js:75:14)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
ERROR: "test:e2e:run" exited with 1.
```

Unfortunately this is the error.

**Comment by moishinetzer** [comment]
![image](https://user-images.githubusercontent.com/11411486/159176419-3b10b6a4-283e-4e0d-89ff-1dce3ea8a9c7.png)

It errors here, however I'm not sure how to save and send the whole debug stack on vscode, if you can explain how, I am happy to do so, I've figured out how to debug it so far...

**Comment by moishinetzer** [comment]
Heres a screen recording:

https://user-images.githubusercontent.com/11411486/159176647-02077e85-79aa-4c6d-a17f-7c894600f497.mp4

**Comment by kentcdodds** [comment]
Could you try the latest version of this stack with Node v16 (instead of v17 which is an unstable version of Node) and let me know whether that fixes the issue?

**Comment by kentcdodds** [comment]
I think I've fixed it now. Could you try again?
