### ISSUE TITLE
Warning: Expected server HTML to contain a matching <script> in <body>.

### ISSUE THREAD

**Issue by jakexconniff** [remix-run/indie-stack#29]
Upon clean install of the Indie Stack, I get this error message in console every time the page loads. It doesn't break anything as far as I can see, but figure it is worth highlighting.

```
Warning: Expected server HTML to contain a matching <script> in <body>.
    at script
    at LiveReload2 (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:3192:3)
    at body
    at html
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:2627:3)
    at Routes2 (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:2610:7)
    at Router (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:304:15)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:1111:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:1036:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:2507:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-RKTPM4MS.js:3240:27)
```

Reproduction steps:

1. `npx create-remix@latest`
2. Name your app. Select Indie Stack when prompted. Hit Y to `npm install`
3. `npm run dev`
4. Visit localhost:3000 in browser and open console
5. Error message should be there

If this is not as easily reproducable for anyone else, then perhaps it is an issue with my OS. But I have tried two separate repos (one, I modified the Indie stack app folder with contents of a previous app I am trying to port over to Indie Stack, and the other one was a clean install following steps above.)

Let me know if any other details would make this easier to dig into, or if I am the only one experiencing the issue.

**Comment by kentcdodds** [comment]
I'm able to reproduce. I'll look into it. Thanks for reporting!

**Comment by maxprilutskiy** [comment]
@kentcdodds I'm doing a clean install of remix using `yarn create remix`, and I see exactly the same issue. Any ideas?

```
"dependencies": {
    "@enprimal/bricks": "^0.0.2",
    "@remix-run/node": "^1.7.5",
    "@remix-run/react": "^1.7.5",
    "@remix-run/vercel": "^1.7.5",
    "@vercel/node": "^2.4.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.7.5",
    "@remix-run/eslint-config": "^1.7.5",
    "@remix-run/serve": "^1.7.5",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "autoprefixer": "^10.4.13",
    "concurrently": "^7.5.0",
    "eslint": "^8.23.1",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.7.4"
  },
  "engines": {
    "node": ">=14"
  }
```

**Comment by maxprilutskiy** [comment]
@kentcdodds I'm doing a clean install of remix using `yarn create remix`, and I see exactly the same issue. Any ideas?

```
"dependencies": {
    "@remix-run/node": "^1.7.5",
    "@remix-run/react": "^1.7.5",
    "@remix-run/vercel": "^1.7.5",
    "@vercel/node": "^2.4.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.7.5",
    "@remix-run/eslint-config": "^1.7.5",
    "@remix-run/serve": "^1.7.5",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "autoprefixer": "^10.4.13",
    "concurrently": "^7.5.0",
    "eslint": "^8.23.1",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.7.4"
  },
  "engines": {
    "node": ">=14"
  }
```
