### ISSUE TITLE
Stack fails setup when precompiled Prisma engines are not available.

### ISSUE THREAD

**Issue by jakehamilton** [remix-run/indie-stack#88]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

On NixOS or in a Nix Shell, run `npx create-remix --template remix-run/indie-stack`

<details>
  <summary>View Output</summary>

```
Need to install the following packages:
  create-remix
Ok to proceed? (y) y
? Where would you like to create your app? ./test-stack
? Do you want me to run `npm install`? Yes
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

added 1328 packages, and audited 1329 packages in 19s

235 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
? TypeScript or JavaScript? TypeScript
💿 Running remix.init script

> setup
> prisma migrate dev && prisma db seed

Warning Precompiled engine files are not available for nixos.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"


The following migration(s) have been applied:

migrations/
  └─ 20220307190657_init/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)
Warning Precompiled engine files are not available for nixos.
TypeError: collection is not iterable
    at keyBy (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:57531:21)
    at Object.getTypeMap (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:59314:17)
    at new DMMFHelper (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:59211:25)
    at new TSClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60494:17)
    at buildClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60740:18)
    at generateClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60811:47)
    at async LineStream.<anonymous> (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:54039:24)


Warning Precompiled engine files are not available for nixos.
Environment variables loaded from .env
Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
/home/short/work/test-stack/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/home/short/work/test-stack/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/home/short/work/test-stack/prisma/seed.ts:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/home/short/work/test-stack/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/short/work/test-stack/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (/home/short/work/test-stack/node_modules/ts-node/src/bin.ts:567:12)

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node --require tsconfig-paths/register prisma/seed.ts
🚨 Oops, remix.init failed

Command failed: npm run setup
```

</details>

---

Investigating a bit, it seems that running `prisma generate` _prior_ to running `npm run setup` will succeed.

1. Run `prisma generate`

<details>
  <summary>View Output</summary>
  
````               
Warning Precompiled binaries are not available for nixos.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Warning Precompiled binaries are not available for nixos.
[Error: ENOENT: no such file or directory, mkdir '/nix/store/vn57rafwfanmrzjndnlcr4q56r55p9k8-prisma-3.12.0/lib/node_modules/prisma/engines'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/nix/store/vn57rafwfanmrzjndnlcr4q56r55p9k8-prisma-3.12.0/lib/node_modules/prisma/engines'
}
Warning Precompiled binaries are not available for nixos.

✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 75ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

warn Versions of prisma@3.12.0 and @prisma/client@3.14.0 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
````

</details>

2. Run `npm run setup`

<details>
  <summary>View Output</summary>
  
```
> setup
> prisma migrate dev && prisma db seed

Warning Precompiled engine files are not available for nixos.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
Warning Precompiled engine files are not available for nixos.
TypeError: collection is not iterable
    at keyBy (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:57531:21)
    at Object.getTypeMap (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:59314:17)
    at new DMMFHelper (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:59211:25)
    at new TSClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60494:17)
    at buildClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60740:18)
    at generateClient (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:60811:47)
    at async LineStream.<anonymous> (/home/short/work/test-stack/node_modules/@prisma/client/generator-build/index.js:54039:24)


Warning Precompiled engine files are not available for nixos.
Environment variables loaded from .env
Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
Database has been seeded. 🌱

🌱  The seed command has been executed.
```

</details>

### Expected Behavior

The stack should not fail due to precompiled Prisma engines not existing. Instead, `prisma generate` should be run first _or_ the Prisma step should be skipped and the reponsibility of performing Prisma setup handed to the user.

### Actual Behavior

When attempting to setup a new project using this Remix Stack, the process fails before completing. Precompiled Prisma engines are not available in a Nix environment due to how packages, linking, and the environment are configured. Instead, it is expected that `prisma generate` is run to generate a client that uses Nix's version of Prisma since Nix environments are typically created per-project [as seen here](https://github.com/prisma/prisma/issues/3026#issuecomment-927258138).

**Comment by jakehamilton** [comment]
There are a few ways this could be handled, so I wanted to hear your folks' thoughts. From my perspective, we could:

a. Always run `prisma generate` first.

I believe that Prisma will use precompiled binaries for supported systems in this case, but I could be wrong. If this introduces waiting time for _everyone else_ then it's not worth it. Though if it is a freebie, then this would be the preferred solution.

b. Try `npm run setup` and retry with `prisma generate` if an error occurred.

A bit more hacky, but it would be possible to attempt running setup first without `prisma generate`. Then, if an error occurred, we could generate the Prisma client and retry. The naive implementation here wouldn't know what error occurred, so it's possible we waste some time if there's another problem with Prisma setup.
