### ISSUE TITLE
interceptors.createInterceptor is not a function

### ISSUE THREAD

**Issue by Vikaskumargd** [remix-run/indie-stack#91]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. clone this repository or run `npx create-remix --template remix-run/indie-stack blog-tutorial` (following this quickstart tutorial https://remix.run/docs/en/v1/tutorials/blog)
2. `npm run dev`

### Expected Behavior

the app should be running on http://localhost:3000/,

### Actual Behavior

throw an error:

`> Executing task: npm run dev <

> dev
> run-p dev:*

> dev:css
> npm run generate:css -- --watch

> dev:remix
> cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev

C:\Users\vikas\source\repos\temp\remix-experiments\indie-stack\node_modules\msw\node\lib\index.js:8143
        const interceptor = interceptors.createInterceptor({
                                         ^

TypeError: interceptors.createInterceptor is not a function
    at setupServer (C:\Users\vikas\source\repos\temp\remix-experiments\indie-stack\node_modules\msw\node\lib\index.js:8143:42)
    at Object.<anonymous> (C:\Users\vikas\source\repos\temp\remix-experiments\indie-stack\mocks\index.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1282:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:539:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:85:3)

> generate:css
> tailwindcss -o ./app/styles/tailwind.css "--watch"

Rebuilding...
Done in 269ms.`

**Comment by MichaelDeBoey** [comment]
Can confirm

https://github.com/remix-run/indie-stack/runs/6536214432?check_suite_focus=true#step:9:53

**Comment by AriPerkkio** [comment]
Any quick work-arounds for this? Trying to get the tutorial running without spending much time debugging. 😄

**Comment by timtruston** [comment]
I just experienced the same here!

**Comment by MichaelDeBoey** [comment]
Problem seems to be with `msw`, so @kettanaito could probably help us out here.

**Comment by kettanaito** [comment]
There's been an issue with one of the MSW dependencies (`@mswjs/interceptors`). The release has been reverted and is now at 0.15.3. Re-installing dependencies will fix the issue.
